CREATE TABLE IF NOT EXISTS CATEGORIES (
    id SERIAL PRIMARY KEY ,
    name VARCHAR (100) NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_on TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    id SERIAL PRIMARY KEY,
    category_id INTEGER NOT NULL,
    name VARCHAR (100) NOT NULL,
    price decimal(12, 2),
    price_type INTEGER NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_on TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL,
    FOREIGN KEY (category_id) REFERENCES CATEGORIES(id)
);