CREATE TABLE IF NOT EXISTS ADAPTIONS (
    id SERIAL PRIMARY KEY ,
    name VARCHAR (100) NOT NULL,
    price decimal(12, 2),
    created_on TIMESTAMP WITH TIME ZONE NOT NULL,
    modified_on TIMESTAMP WITH TIME ZONE,
    registered BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS_ADAPTION_MAPPINGS (
    product_id INTEGER NOT NULL,
    adaption_id INTEGER NOT NULL,
    FOREIGN KEY (product_id) REFERENCES PRODUCTS(id),
    FOREIGN KEY (adaption_id) REFERENCES ADAPTIONS(id)
);

CREATE TABLE IF NOT EXISTS PRODUCT_ORDER_ADAPTION_MAPPINGS (
    product_order_id INTEGER NOT NULL,
    adaption_id INTEGER NOT NULL,
    FOREIGN KEY (product_order_id) REFERENCES PRODUCT_ORDER(id),
    FOREIGN KEY (adaption_id) REFERENCES ADAPTIONS(id)
);